name: educational_app
description: setData education application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  build_runner: ^2.1.11
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  get: ^4.6.3
  glassmorphism: ^3.0.0
  google_fonts: ^3.0.0
  http: ^0.13.4
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  shared_preferences: ^2.0.15
  video_player: ^2.1.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
